#!/usr/bin/env python3
"""Generates app/themes.css from the token table in lib/theme.ts.

    python3 scripts/build-theme-css.py

A theme is a set of token values (see lib/theme.ts). They have to exist twice —
as CSS custom properties for the components, and as literals in TypeScript for
the chart library, which cannot read variables — so one side is generated from
the other and lib/theme.test.ts asserts the two never drift apart.

Only app/themes.css is generated; everything else in app/globals.css is written
by hand.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "lib/theme.ts"
TARGET = ROOT / "app/themes.css"


def parse_block(name: str) -> dict:
    """Read one `export const <name>: ... = { … };` object literal as JSON."""
    text = SOURCE.read_text(encoding="utf-8")
    start = text.index(f"export const {name}")
    body = text[text.index("{", start):]
    depth = 0
    for i, ch in enumerate(body):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                body = body[: i + 1]
                break
    # TS object literal → JSON: drop comments, quote the keys, normalize the
    # string quotes (a font stack legitimately contains double quotes, so those
    # entries are single-quoted in the source) and drop trailing commas.
    body = re.sub(r"//[^\n]*", "", body)
    for _ in range(2):  # twice, so keys directly after "{" are caught too
        body = re.sub(r"([{,]\s*)([A-Za-z_]\w*):", r'\1"\2":', body)
    body = re.sub(
        r"'([^']*)'",
        lambda m: json.dumps(m.group(1)),
        body,
    )
    body = re.sub(r",(\s*[}\]])", r"\1", body)
    return json.loads(body)


THEMES = parse_block("THEMES")
META = parse_block("THEME_META")
CSS_VARS = parse_block("THEME_CSS_VARS")
DEFAULT = re.search(
    r'export const DEFAULT_THEME: ThemeId = "(\w+)"', SOURCE.read_text(encoding="utf-8")
).group(1)


def block(selector: str, theme: str, indent: str = "  ") -> str:
    tokens = THEMES[theme]
    meta = META[theme]
    lines = [f"{selector} {{"]
    lines.append(f"{indent}color-scheme: {meta['scheme']};")
    for key, var in CSS_VARS.items():
        lines.append(f"{indent}{var}: {tokens[key]};")
    for i, colour in enumerate(tokens["chart"], start=1):
        lines.append(f"{indent}--chart-{i}: {colour};")
    if meta.get("fontBody"):
        lines.append(f"{indent}--theme-font-body: {meta['fontBody']};")
    if meta.get("fontHeading"):
        lines.append(f"{indent}--theme-font-heading: {meta['fontHeading']};")
    lines.append("}")
    return "\n".join(lines)


out = [
    "/* Generated by scripts/build-theme-css.py from lib/theme.ts — do not edit.",
    " *",
    " * One block per theme, each a complete set of the design tokens every",
    " * component styles itself with. The default theme is also on :root, so the",
    " * prerendered HTML is themed before any attribute is set.",
    " */",
    "",
    block(f':root,\n[data-theme="{DEFAULT}"]', DEFAULT),
]
for theme in THEMES:
    if theme == DEFAULT:
        continue
    out.append("")
    out.append(block(f'[data-theme="{theme}"]', theme))

PRINT = re.search(
    r'export const PRINT_THEME: ThemeId = "(\w+)"', SOURCE.read_text(encoding="utf-8")
).group(1)

out += [
    "",
    "/* Print and PDF export always use the light paper theme, whatever is on",
    "   screen: ink on white, and no dark background flooding a page. The",
    "   attribute selector outweighs the per-theme blocks above. */",
    "@media print {",
    "\n".join(
        "  " + line
        for line in block("html,\nhtml[data-theme]", PRINT, indent="  ").split("\n")
    ),
    "}",
    "",
    "/* Colour-vision-friendly mode: gain moves from green to a blue that stays",
    "   apart from the loss colour for every common form of colour blindness.",
    "   One rule, per-theme value — the themes carry the blue themselves. */",
    '[data-colorblind="safe"] {',
    "  --gain: var(--gain-safe);",
    "}",
    "",
]

TARGET.write_text("\n".join(out), encoding="utf-8")
print(f"wrote {TARGET.relative_to(ROOT)} ({len(THEMES)} themes)")
